### ISSUE TITLE
视频长简介加载不完整

### ISSUE THREAD

**Issue by cqjjjzr** [MotooriKashin/Bilibili-Old#180]
## 环境

- 插件版本 5.2.3
- TamperMonkey v4.13
- Chrome 94.0.4606.61
- Windows 10 19043

## 问题

在具有长简介的视频（需要点“展开更多”的）中，Bilibili-Old 启用时仅显示了简介的前 6 行。

## 测试视频

https://www.bilibili.com/video/av847547649

请比较启用/禁用 Bilibili-Old 时的行为。

**Comment by cqjjjzr** [comment]
此问题大概率由这个 CSS 引起：`https://s1.hdslb.com/bfs/static/jinkela/videoplay/css/video.0.406cee7878545872b8dfbe73071d665dfb287c67.css`

其中有：  
```css
.video-desc-m .info {
    white-space: pre-line;
    transition: all .3s;
    line-height: 20px;
    color: #6d757a;
    height:120px;
    overflow: hidden;
}
```

去掉其中 `height:120px;` 即显示正常。

**Comment by MotooriKashin** [comment]
不是有“展开更多”的选项吗？
![2021-10-05_070541](https://user-images.githubusercontent.com/60416767/135936255-7ca3654e-1976-43e3-a64c-2b249cce2927.png)

**Comment by cqjjjzr** [comment]
我的锅。。貌似加载的 UserCSS 和旧版页面不兼容

**Comment by cqjjjzr** [comment]
具体的说，是 "Bilibili显示全标题" 这个 UserCSS。其中的 L68~L71:

```css
[report-id="abstract_spread"],
[report-id="abstract_unspread"] {
    display: none !important;
}
```

导致了这个问题。可以考虑把这一情况在文档中提出来。
