### ISSUE TITLE
[Feature Requset] 三连效果提供

### ISSUE THREAD

**Issue by Sonic853** [MotooriKashin/Bilibili-Old#307]
**存在问题**
无三连

**目标愿景**
三连实现

**参考建议**
从新版页面的三连里提取了长按点赞的抖动效果，但由于三连时投币和收藏的环是用canvas做的，暂时不知道这么提取，不过那个环还是可以用CSS动画制作

**补充内容**
![biligif](https://user-images.githubusercontent.com/8389962/170179666-3a33bc67-8934-440c-8734-e296fa8e40cf.gif)

```CSS
/* 点击一下时为点赞，按下超过大约一秒时开始触发预备三连动画。
触发预备三连时应加shake的class，
在预备三连时鼠标移开位置或松开鼠标应中断三连，同时不能触发点赞效果。
三连完成时应有三连完成提示 */
.ulike.shake svg{
    animation: shake 1500ms ease-in-out infinite;
}
@keyframes shake {
    2% {
        transform: translate(0.5px, -0.5px) rotate(0.5deg);
    }
    4% {
        transform: translate(-0.5px, 2.5px) rotate(0.5deg);
    }
    6% {
        transform: translate(-1.5px, 2.5px) rotate(-0.5deg);
    }
    8% {
        transform: translate(-1.5px, 0.5px) rotate(1.5deg);
    }
    10% {
        transform: translate(1.5px, 2.5px) rotate(0.5deg);
    }
    12% {
        transform: translate(-1.5px, 2.5px) rotate(1.5deg);
    }
    14% {
        transform: translate(1.5px, 1.5px) rotate(-0.5deg);
    }
    16% {
        transform: translate(2.5px, -0.5px) rotate(1.5deg);
    }
    18% {
        transform: translate(1.5px, 0.5px) rotate(0.5deg);
    }
    20% {
        transform: translate(1.5px, -1.5px) rotate(-0.5deg);
    }
    22% {
        transform: translate(-1.5px, -1.5px) rotate(-0.5deg);
    }
    24% {
        transform: translate(-0.5px, -1.5px) rotate(0.5deg);
    }
    26% {
        transform: translate(-1.5px, 2.5px) rotate(-0.5deg);
    }
    28% {
        transform: translate(2.5px, 1.5px) rotate(1.5deg);
    }
    30% {
        transform: translate(0.5px, -0.5px) rotate(1.5deg);
    }
    32% {
        transform: translate(1.5px, 2.5px) rotate(1.5deg);
    }
    34% {
        transform: translate(-1.5px, -1.5px) rotate(-0.5deg);
    }
    36% {
        transform: translate(-0.5px, 0.5px) rotate(-0.5deg);
    }
    38% {
        transform: translate(1.5px, -1.5px) rotate(1.5deg);
    }
    40% {
        transform: translate(-0.5px, 0.5px) rotate(1.5deg);
    }
    42% {
        transform: translate(2.5px, -0.5px) rotate(1.5deg);
    }
    44% {
        transform: translate(-1.5px, 2.5px) rotate(0.5deg);
    }
    46% {
        transform: translate(-0.5px, 2.5px) rotate(-0.5deg);
    }
    48% {
        transform: translate(1.5px, -0.5px) rotate(1.5deg);
    }
    50% {
        transform: translate(1.5px, -0.5px) rotate(1.5deg);
    }
    52% {
        transform: translate(0.5px, 0.5px) rotate(-0.5deg);
    }
    54% {
        transform: translate(-0.5px, -1.5px) rotate(-0.5deg);
    }
    56% {
        transform: translate(1.5px, -1.5px) rotate(1.5deg);
    }
    58% {
        transform: translate(0.5px, 1.5px) rotate(1.5deg);
    }
    60% {
        transform: translate(-0.5px, -0.5px) rotate(1.5deg);
    }
    62% {
        transform: translate(-0.5px, 0.5px) rotate(1.5deg);
    }
    64% {
        transform: translate(0.5px, -0.5px) rotate(1.5deg);
    }
    66% {
        transform: translate(2.5px, 0.5px) rotate(1.5deg);
    }
    68% {
        transform: translate(1.5px, -0.5px) rotate(1.5deg);
    }
    70% {
        transform: translate(0.5px, 2.5px) rotate(1.5deg);
    }
    72% {
        transform: translate(1.5px, -0.5px) rotate(0.5deg);
    }
    74% {
        transform: translate(2.5px, -0.5px) rotate(0.5deg);
    }
    76% {
        transform: translate(2.5px, -0.5px) rotate(1.5deg);
    }
    78% {
        transform: translate(-1.5px, -0.5px) rotate(-0.5deg);
    }
    80% {
        transform: translate(-1.5px, 0.5px) rotate(-0.5deg);
    }
    82% {
        transform: translate(-1.5px, 2.5px) rotate(0.5deg);
    }
    84% {
        transform: translate(-0.5px, 0.5px) rotate(1.5deg);
    }
    86% {
        transform: translate(-1.5px, 1.5px) rotate(0.5deg);
    }
    88% {
        transform: translate(-0.5px, -0.5px) rotate(1.5deg);
    }
    90% {
        transform: translate(-1.5px, -1.5px) rotate(1.5deg);
    }
    92% {
        transform: translate(2.5px, 1.5px) rotate(0.5deg);
    }
    94% {
        transform: translate(2.5px, 1.5px) rotate(-0.5deg);
    }
    96% {
        transform: translate(2.5px, -0.5px) rotate(0.5deg);
    }
    98% {
        transform: translate(1.5px, 0.5px) rotate(-0.5deg);
    }
    0%,
      100% {
        transform: translate(0, 0) rotate(0);
    }
}
```
